apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwce-cicd-deployment
spec:
  selector:
    matchLabels:
      app: bwce-cicd
  template:
    metadata:
      labels:
        app: bwce-cicd
    spec:
      containers:
      - name: bwce-cicd
        image: mpandav/bwce_cicd.jenkins-build:148
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8096

---

apiVersion: v1
kind: Service
metadata:
  name: bwce-cicd-service
spec:
  type: ClusterIP
  selector:
    app: bwce-cicd
  ports:
  - port: 80
    targetPort: 8064
    name: 80-8064
    protocol: TCP

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bwce-cicd
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bwce-cicd-service
            port:
              number: 80